/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppPagination: typeof import('./components/common/AppPagination.vue')['default']
    CodeEditor: typeof import('./components/common/CodeEditor.vue')['default']
    ConfirmModal: typeof import('./components/common/ConfirmModal.vue')['default']
    DataTable: typeof import('./components/common/DataTable.vue')['default']
    DiffEditor: typeof import('./components/common/DiffEditor.vue')['default']
    DiscoveryChainView: typeof import('./components/consul/DiscoveryChainView.vue')['default']
    FilterBar: typeof import('./components/common/FilterBar.vue')['default']
    FormModal: typeof import('./components/common/FormModal.vue')['default']
    McpToolSelector: typeof import('./components/ai/McpToolSelector.vue')['default']
    PipelineStatusDisplay: typeof import('./components/ai/PipelineStatusDisplay.vue')['default']
    PromptDebugPanel: typeof import('./components/ai/PromptDebugPanel.vue')['default']
    PromptOptimizeDialog: typeof import('./components/ai/PromptOptimizeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceTopologyGraph: typeof import('./components/consul/ServiceTopologyGraph.vue')['default']
    ShowCodeDialog: typeof import('./components/common/ShowCodeDialog.vue')['default']
    SkillOptimizeDialog: typeof import('./components/ai/SkillOptimizeDialog.vue')['default']
    ToastMessage: typeof import('./components/feedback/ToastMessage.vue')['default']
  }
}
