/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppPagination: typeof import('./components/common/AppPagination.vue')['default']
    CodeEditor: typeof import('./components/common/CodeEditor.vue')['default']
    ConfirmModal: typeof import('./components/common/ConfirmModal.vue')['default']
    DataTable: typeof import('./components/common/DataTable.vue')['default']
    FilterBar: typeof import('./components/common/FilterBar.vue')['default']
    FormModal: typeof import('./components/common/FormModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastMessage: typeof import('./components/feedback/ToastMessage.vue')['default']
  }
}
